-- Table: public.roles

DROP TABLE IF EXISTS public.roles;

CREATE TABLE IF NOT EXISTS public.roles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.roles
    OWNER to postgres;


INSERT INTO roles
VALUES (1,'Rol Administrador', 'ADMIN')
ON CONFLICT (id) DO NOTHING;

INSERT INTO roles
VALUES (2,'Rol usuario', 'USER')
ON CONFLICT (id) DO NOTHING;